
[functions.submit_move]
enabled = true
verify_jwt = true
import_map = "./functions/submit_move/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit_move/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit_move/*.html" ]

[functions.api-docs]
enabled = true
verify_jwt = true
import_map = "./functions/api-docs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/api-docs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/api-docs/*.html" ]

[functions.create-game]
verify_jwt = false

[functions.get-games]
verify_jwt = false

[functions.resign-game]
verify_jwt = false

[functions.submit-move]
verify_jwt = false
